modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="cuando_el_cielo_tenia_mas_colore"
version="1.0.0"
displayName="Cuando el cielo tenia mas colores"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="imcap, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.cuando_el_cielo_tenia_mas_colore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration